kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Release.Name }}
  namespace: mysql
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app.kubernetes.io/instance: {{ .Release.Name }}
      - podSelector:
          matchLabels:
            purpose: job
      - namespaceSelector:
          matchLabels:
            purpose: k8s
      - namespaceSelector:
          matchLabels:
            purpose: forwarding
        podSelector:
          matchLabels:
            app.kubernetes.io/instance: {{ .Release.Name }}
