kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  labels:
    app: {{ .Release.Name }}
  name: {{ .Release.Name }}
  namespace: mysql
spec:
  podSelector:
    matchLabels:
      app: {{ .Release.Name }}
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app: {{ .Release.Name }}