apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}
  namespace: services
  labels:
    {{- include "mysql-chart.labels" . | nindent 4 }}
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: Never
    ports:
    - containerPort: 80
