apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-pv-volume
  namespace: mysql
spec:
  storageClassName: local-storage
  claimRef:
    name: {{ .Release.Name }}-pvc
    namespace: mysql
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: "/data/{{ .Release.Name }}-binlogs"