apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-pv-volume
  namespace: mysql
  labels:
    type: local
spec:
  storageClassName: ""
  claimRef:
    name: {{ .Release.Name }}-pvc
    namespace: mysql
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data"