kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-pvc
  namespace: mysql
spec:
  volumeMode: Filesystem
  volumeName: {{ .Release.Name }}-pv-volume
  storageClassName: ""
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      volume: {{ .Release.Name }}-pv-volume