kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-pvc
  namespace: mysql
spec:
  volumeMode: Filesystem
  volumeName: {{ .Release.Name }}-pv-volume
  storageClassName: ""
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      volume: {{ .Release.Name }}-pv-volume