apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: services
  labels:
    {{- include "mysql-chart.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
  selector:
    {{- include "mysql-chart.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mysql-chart.fullname" . }}
  namespace: mysql
  labels:
    {{- include "mysql-chart.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: tcp
      port: 3306
      targetPort: 3306
  selector:
    {{- include "mysql-chart.selectorLabels" . | nindent 4 }}
