apiVersion: v1
kind: Service
metadata:
  name: {{ include "mysql-chart.fullname" . }}
  namespace: mysql
  labels:
    {{- include "mysql-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: tcp
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
    - port: 2888
      name: server
    - port: 3888
      name: leader-election
  selector:
    {{- include "mysql-chart.selectorLabels" . | nindent 4 }}