#!/bin/bash
### BEGIN INIT INFO
# Provides: 		mysync-init
# Required-Start:	$remote_fs $syslog
# Required-Stop:	$remote_fs $syslog
# Should-Start:		$network $time
# Should-Stop:		$network $time
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description: 	work with mysync
# Description:		work with mysync
#
### END INIT INFO

start() {
	mysync >> /var/log/mysync.log 2>&1 &
}

stop() {
	pkill mysync
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		stop
		start
		;;
	status)
		if ps | pgrep mysync | wc -l; then
			exit 1
		else
			exit 0
		fi
		;;
	*)
		echo "Usage: $0 {start|stop|status|restart}"
esac

exit 0
